---
title: "Untitled"
format: html
---


```{r}
library(tidyverse)
library(lubridate)
library(knitr)
library(data.table)
library(ggplot2)
library(hms)

pretty <- function(x) {
    as_hms(as.numeric(x))
}

dt <- read_csv("data.csv")

sleep <- dt |>
  filter(Type == "Sleep") |>
  mutate(
    start = ymd_hms(Start),
    end = ymd_hms(End),
    duration = as.duration(hm(Duration)),
    duration_pretty = Duration,
    city = case_when(
      date(start) >= dmy("13/11/2025") & date(start) <= dmy("26/11/2025") ~ "Salvador",
      date(start) >= dmy("27/11/2025") & date(start) <= dmy("01/12/2025") ~ "São Paulo",
      TRUE ~ "Belo Horizonte"
    )
  ) |>
  mutate(
    start_hour = hour(start),
    time = case_when(
      start_hour >= 18 ~ "noite",  # Evening sleep
      start_hour < 6 ~ "noite",    # Early morning sleep
      TRUE ~ "dia"
    ),
    day = case_when(
      start_hour < 6 ~ date(start) - days(1),
      TRUE ~ date(start)
    )
  ) |>
  select(-start_hour) |>
  select(day, time, duration, duration_pretty, start, end, city) |>
  arrange(start) |> 
  filter(start >= dmy("05/11/2025"))

# fwrite(sleep, "sleep.csv")
```

## Sono

- 06/11 - 12/11 (Belo Horizonte)
- 13/11 - 26/11 (Salvador)
- 27/11 - 01/12 (São Paulo)
- 02/12 - 09/12 (Belo Horizonte)

```{r}
sleep_manual <- fread("sleep.csv") |> mutate(duration = duration(duration))
day_sleep <- sleep_manual |> filter(time == "dia")
night_sleep <- sleep_manual |> filter(time == "noite")
```


```{r}
day_sleep |>
  group_by(day, time) |>
  summarise(
    total_duration = duration(sum(duration)),
    sleep_blocks = n(),
    max_block_duration = duration(max(duration)),
    avg_block_duration = duration(mean(duration)),
    .groups = "drop"
  ) |> kable()
```


```{r}
night_sleep_agg <- night_sleep |>
  select(-time) |> 
  group_by(day, city) |>
  summarise(
    total_duration = pretty(duration(sum(duration))),
    sleep_blocks = n(),
    max_block_duration = pretty(duration(max(duration))),
    avg_block_duration = pretty(duration(mean(duration))),
    .groups = "drop"
  )

writexl::write_xlsx(night_sleep_agg, "night_sleep_agg.xlsx")  
```

